trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'macos-latest'

variables:
  scheme: 'CryptoPrices'
  project: 'CryptoPrices.xcodeproj'
  testCoverageThreshold: 85

stages:
  - stage: BuildAndTest
    jobs:
      - job: Build
        steps:
          - checkout: self

          - script: |
              echo "Building Xcode project..."
              xcodebuild -project $(project) \
                         -scheme $(scheme) \
                         -sdk iphonesimulator \
                         -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.4' \
                         CODE_SIGN_IDENTITY="" \
                         CODE_SIGNING_REQUIRED=NO \
                         build
            displayName: 'Build Xcode project'

          - script: |
              echo "Running unit tests with coverage..."
              xcodebuild test \
                         -project $(project) \
                         -scheme $(scheme) \
                         -sdk iphonesimulator \
                         -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.4' \
                         -enableCodeCoverage YES \
                         | tee xcode-test.log
            displayName: 'Run Unit Tests with Coverage'
